/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.vehiculos.ventanas;

import ar.com.baseDeDatos.AdministradorDeConexiones;
import ar.com.vehiculos.entidades.CustomListModelVendedores;
import ar.com.vehiculos.entidades.Vendedor;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Daiana
 */
public class vendedoresVentana extends javax.swing.JInternalFrame {

    /**
     * Creates new form vendedoresVentana
     */
    // Creo lista para mostrar
    CustomListModelVendedores list_model = new CustomListModelVendedores();
    public vendedoresVentana() throws Exception {
        initComponents();
        
        // Seteo list para cargar por defecto
        llenarListaDeVendedores();
        
        // Desabilito botones guardar y eliminar
        btn_guardar.setEnabled(false);
        btn_eliminar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_listaVendedores = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_apellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_documento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_autosVendidos = new javax.swing.JTextField();
        btn_nuevo = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_cerrar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Lista de Vendedores");

        list_listaVendedores.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        list_listaVendedores.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                list_listaVendedoresValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(list_listaVendedores);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel3.setText("Apellido");

        txt_apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_apellidoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel4.setText("DNI");

        txt_documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_documentoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel5.setText("Autos vendidos");

        btn_nuevo.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btn_nuevo.setText("Nuevo");
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });

        btn_guardar.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        btn_eliminar.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_cerrar.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btn_cerrar.setText("Cerrar");
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_eliminar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_documento, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_autosVendidos, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(11, 11, 11))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_autosVendidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void llenarListaDeVendedores() throws Exception{
        // Obtengo una conexion
        Connection unaConexion = AdministradorDeConexiones.obtenerConexion();
        
        // Armo la query
        String unaConsulta = "select * from vendedores";
        
        // Creo un objeto de tipo Statement que ejecutara la sentencia
        Statement unaSentencia = unaConexion.createStatement();
        
        // Ejecuto la senetencia y almaceno el resultado en un objeto de tipo ResulSet
        ResultSet unResultado = unaSentencia.executeQuery(unaConsulta);
        
        // Recorro el resultado y lo imprimo en consola
        while(unResultado.next()){
            int idvendedores = unResultado.getInt("idvendedores");
            String nombre = unResultado.getString("nombre");
            String apellido = unResultado.getString("apellido");
            int numeroDocumento = unResultado.getInt("numeroDocumento");
            int cantAutosVendidos = unResultado.getInt("cantAutosVendidos");
            
            Vendedor unVendedor = new Vendedor(cantAutosVendidos, idvendedores, nombre, apellido, numeroDocumento);
            list_model.agregarPersona(unVendedor);
        }
        // Cierro la sentencia
        unaSentencia.close();
        unaConexion.close();
        
        list_listaVendedores.setModel(list_model);
    }
    
    private void txt_documentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_documentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_documentoActionPerformed

    private void txt_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_apellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_apellidoActionPerformed

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed
        //Boton cerrar cierra venta en cuestion
        this.hide();
    }//GEN-LAST:event_btn_cerrarActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        //Tomo valor de caja de texto
        String nombre = txt_nombre.getText();
        String apellido = txt_apellido.getText();
        String documento = txt_documento.getText();
        String autosVendidos = txt_autosVendidos.getText();
        
        //Valido que no este vacio
        if(nombre.isEmpty()){
            // Si nombre esta vacio muestro caja de dialogo
            JOptionPane.showMessageDialog(null, "El nombre no puede estar vacio", "Alerta", JOptionPane.WARNING_MESSAGE);
            // Pongo el foco en nombre
            txt_nombre.requestFocus();
        }
        else if(apellido.isEmpty()){
            JOptionPane.showMessageDialog(null, "El apellido no puede estar vacio", "Alerta", JOptionPane.WARNING_MESSAGE);
            txt_apellido.requestFocus();
        }
        else if(documento.isEmpty()){
            JOptionPane.showMessageDialog(null, "El documento no puede estar vacio", "Alerta", JOptionPane.WARNING_MESSAGE);
            txt_documento.requestFocus();
        }
        //Valido que dato ingresado sea numero
        else if(!documento.matches("[0-9]*")){
            // Si documento no es numero muestro caja de dialogo
            JOptionPane.showMessageDialog(null, "El documento debe ser un numero entero", "Alerta", JOptionPane.WARNING_MESSAGE);
            // Pongo foco en documento
            txt_documento.requestFocus();
            // Limpio caja de texto
            txt_documento.setText(null);           
        }
        else if(autosVendidos.isEmpty()){
            JOptionPane.showMessageDialog(null, "La cantidad de autos vendidos no puede estar vacio", "Alerta", JOptionPane.WARNING_MESSAGE);
            txt_autosVendidos.requestFocus();
        }
        else if(!autosVendidos.matches("[0-9]*")){
            JOptionPane.showMessageDialog(null, "La cant. de autos vendidos debe ser un numero entero", "Alerta", JOptionPane.WARNING_MESSAGE);
            txt_autosVendidos.requestFocus();
            txt_autosVendidos.setText(null);           
        }
        else{
            //Si todo esta completo: guardo, limpio cajas de texto, habilito boton nuevo y desabilito boton guardar
            JOptionPane.showMessageDialog(null, "El vendedor ha sido guardado");
            txt_nombre.setText(null);
            txt_apellido.setText(null);
            txt_documento.setText(null);
            txt_autosVendidos.setText(null);
            
            btn_nuevo.setEnabled(true);
            btn_guardar.setEnabled(false);
            
            // Parseo presupuesto y documento
            int cantAutosVendidos = Integer.parseInt(autosVendidos);
            int numeroDocumento = Integer.parseInt(documento);
            
            // Instancio nuevo comprador
            Vendedor p = new Vendedor();
            p.setNombre(nombre);
            p.setApellido(apellido);
            p.setNumeroDocumento(numeroDocumento);
            p.setCantAutosVendidos(cantAutosVendidos);
            try {
                int idvendedores = 0;
                list_model.agregarPersonaDB(p, idvendedores, nombre, apellido, numeroDocumento, cantAutosVendidos);
            } catch (Exception ex) {
                Logger.getLogger(vendedoresVentana.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        // Elimino auto
        int selection = list_listaVendedores.getSelectedIndex();
        int resp = JOptionPane.showConfirmDialog(null, "Desea eliminar el Vendedor seleccionado?", "Elija una opcion", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (selection!=-1 && resp == 0) {
            try {
                Vendedor p = list_model.getPersona(selection);
                list_model.eliminarPersona(p, selection);
                btn_eliminar.setEnabled(false);
                JOptionPane.showMessageDialog(null, "El Vendedor ha sido eliminado");
                txt_nombre.setText(null);
                txt_apellido.setText(null);
                txt_documento.setText(null);
                txt_autosVendidos.setText(null);
                btn_guardar.setEnabled(false);
            } catch (Exception ex) {
                Logger.getLogger(vendedoresVentana.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        //Limpio area de textos al precionar boton nuevo
        txt_nombre.setText(null);
        txt_apellido.setText(null);
        txt_documento.setText(null);
        txt_autosVendidos.setText(null);
        
        //Al presionar boton nuevo pasa a desabilitarse
        btn_nuevo.setEnabled(false);
        
        //Al presionar boton nuevo se habilita boton guardar
        btn_guardar.setEnabled(true);
        
        //Al presionar boton nuevo el foco se pone en nombre
        txt_nombre.requestFocus();
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void list_listaVendedoresValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_list_listaVendedoresValueChanged
        // Selecciono y muestro datos de auto guardado
        int selection = list_listaVendedores.getSelectedIndex();
        if (selection!=-1) {            
            Vendedor p = list_model.getPersona(selection);
            txt_nombre.setText(p.getNombre());
            txt_apellido.setText(p.getApellido());
            txt_documento.setText(Integer.toString(p.getNumeroDocumento()));
            txt_autosVendidos.setText(Integer.toString(p.getCantAutosVendidos()));
            
            // Habilito boton eliminar
            btn_eliminar.setEnabled(true);
        }
    }//GEN-LAST:event_list_listaVendedoresValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> list_listaVendedores;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_autosVendidos;
    private javax.swing.JTextField txt_documento;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
