/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.aplicacionConcesionaria.vehiculos.ventanas;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Daiana
 */
public class ventanaMaestra extends javax.swing.JFrame {

    /**
     * Creates new form ventanaMaestra
     */
    public ventanaMaestra() {
        initComponents();
        
        // Maximizo la vista
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        abrirVentana = new javax.swing.JMenu();
        autos = new javax.swing.JRadioButtonMenuItem();
        vendedores = new javax.swing.JRadioButtonMenuItem();
        compradores = new javax.swing.JRadioButtonMenuItem();
        ayuda = new javax.swing.JMenu();
        jRadioButtonMenuItem4 = new javax.swing.JRadioButtonMenuItem();
        configuracion = new javax.swing.JRadioButtonMenuItem();
        salir = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        abrirVentana.setText("Abrir Ventana");
        abrirVentana.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        abrirVentana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirVentanaActionPerformed(evt);
            }
        });

        autos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        autos.setSelected(true);
        autos.setText("Autos");
        autos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autosActionPerformed(evt);
            }
        });
        abrirVentana.add(autos);

        vendedores.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        vendedores.setSelected(true);
        vendedores.setText("Vendedores");
        vendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendedoresActionPerformed(evt);
            }
        });
        abrirVentana.add(vendedores);

        compradores.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        compradores.setSelected(true);
        compradores.setText("Compradores");
        compradores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compradoresActionPerformed(evt);
            }
        });
        abrirVentana.add(compradores);

        jMenuBar2.add(abrirVentana);

        ayuda.setText("Ayuda");
        ayuda.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jRadioButtonMenuItem4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jRadioButtonMenuItem4.setSelected(true);
        jRadioButtonMenuItem4.setText("Ayuda on-line");
        ayuda.add(jRadioButtonMenuItem4);

        configuracion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        configuracion.setSelected(true);
        configuracion.setText("Configuración");
        configuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configuracionActionPerformed(evt);
            }
        });
        ayuda.add(configuracion);

        salir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        salir.setSelected(true);
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        ayuda.add(salir);

        jMenuBar2.add(ayuda);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendedoresActionPerformed
        //Abre ventana vendedores
        vendedoresVentana vv = null;
        try {
            vv = new vendedoresVentana();
        } catch (Exception ex) {
            Logger.getLogger(ventanaMaestra.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDesktopPane1.add(vv);
        vv.setVisible(true);
        vv.setLocation(350, 150);
    }//GEN-LAST:event_vendedoresActionPerformed

    private void abrirVentanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirVentanaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abrirVentanaActionPerformed

    private void autosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autosActionPerformed
        try {
            //Abre ventana autos
            autosVentana av = new autosVentana();
            jDesktopPane1.add(av);
            av.setVisible(true);
            av.setLocation(350, 50);
        } catch (Exception ex) {
            Logger.getLogger(ventanaMaestra.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_autosActionPerformed

    private void compradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compradoresActionPerformed
        //Abre ventana compradores
        compradoresVentana cv = null;
        try {
            cv = new compradoresVentana();
        } catch (Exception ex) {
            Logger.getLogger(ventanaMaestra.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDesktopPane1.add(cv);
        cv.setVisible(true);
        cv.setLocation(350, 150);
    }//GEN-LAST:event_compradoresActionPerformed

    private void configuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configuracionActionPerformed
        //Abre ventana configuracion
        configuracionVentana c = new configuracionVentana();
        jDesktopPane1.add(c);
        c.setVisible(true);
        c.setLocation(400, 150);
    }//GEN-LAST:event_configuracionActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaMaestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaMaestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaMaestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaMaestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaMaestra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu abrirVentana;
    private javax.swing.JRadioButtonMenuItem autos;
    private javax.swing.JMenu ayuda;
    private javax.swing.JRadioButtonMenuItem compradores;
    private javax.swing.JRadioButtonMenuItem configuracion;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem4;
    private javax.swing.JRadioButtonMenuItem salir;
    private javax.swing.JRadioButtonMenuItem vendedores;
    // End of variables declaration//GEN-END:variables
}
